Add carto-cloud-native typings
CartoDB/carto-react pull request #147
Opened 2021-05-27 09:05 UTC by AdriSolid

Add new carto-cloud-native typings

2021-05-27 16:46 UTC, alasarr requested changes
Let's make clearer the difference between carto vs cartoCloudNative credentials.

I've also found we have a type like this:
```
export enum SourceTypes {
  SQL = 'sql',
  BIGQUERY = 'bigquery'
}
```
And it's used in some tests. It should use the [MAP_TYPES defined in @carto/deck.gl](https://github.com/CartoDB/carto-deck.gl/blob/carto-cloud-native/modules/carto/src/api/maps-api-common.js#L4)

2021-05-27 16:46 UTC, alasarr commented on packages/react-api/src/types.d.ts
>  export type Credentials = {
Let's do something like this, to separate credentials for v1 and v2.
```javascript
interface CredentialsCarto {
  apiVersion: API_VERSIONS.V1 | API_VERSIONS.V2,
  username: string,
  apiKey: string,
  region?: string,
  mapsUrl?: string,
  serverUrlTemplate?: string
}

interface CredentialsCartoCloudNative {
  apiVersion: API_VERSIONS.V3,
  apiBaseUrl: string,
  accessToken?: string,
}

export type Credentials = CredentialsCarto | CredentialsCartoCloudNative;
```

2021-05-27 16:48 UTC, alasarr commented
References to SourceTypes.SQL should be removed

2021-06-07 17:33 UTC, VictorVelarde approved these changes
👍🏻

2021-06-07 17:35 UTC, merged