WRAPPER WIDGET Configurable margin in widgets [sc-196869]
CartoDB/carto-react pull request #251
Opened 2021-12-23 16:00 UTC by atoom75

Allow to pass `margin` as props for `WrapperWidgetUI`

2021-12-28 11:36 UTC, alasarr approved these changes

2021-12-28 11:57 UTC, padawannn requested changes
I like the approach but with default values, all widgets are 14px lower in height than the current widgets. I'm wondering if our current widgets are wrong or we need to fix it in this PR

2021-12-28 11:57 UTC, padawannn commented on packages/react-ui/src/widgets/WrapperWidgetUI.js
> +  header: ({ expanded, margin }) => ({
This margin is never used

2021-12-28 12:28 UTC, Clebal commented
In DrawingToolWidgetUI, we use className prop to override default root styles. It has more possibilities than only margin. What do you think guys? @alasarr @padawannn @atoom75

2021-12-29 09:08 UTC, padawannn commented
> In DrawingToolWidgetUI, we use className prop to override default root styles. It has more possibilities than only margin. What do you think guys? @alasarr @padawannn @atoom75

We already had a meeting about this and the idea of this is precisely not to be able to overwrite all the widget styles

2021-12-29 09:20 UTC, padawannn approved these changes
After talking with @alasarr we've decided that we can live with these 14px of height difference

2021-12-29 12:58 UTC, merged