Feature/ch145206/input file
CartoDB/carto-react pull request #276
Opened 2022-01-13 13:05 UTC by builtbyedgar

2022-01-17 16:35 UTC, Josmorsot requested changes
Try to use forEach instead.

LGTM, just minor suggestions

2022-01-17 16:35 UTC, Josmorsot commented on packages/react-ui/src/custom-components/InputFile.js
> +    for (let i = 0; i < items.length; i++) {
Why are you not using a forEach instead?

I would change it for:

```ts
items.forEach(item => { .... })
```

Also I think that would be better to move this block to a new function, something like that:
```ts
// handleDrop function
const newFiles = getAllFiles(items)
props.onChange(newFiles)
```

2022-01-18 19:11 UTC, VictorVelarde commented
Same here @builtbyedgar. Tell us if you'll be able to have availability to fix comments soon or not, please

2022-01-20 15:24 UTC, VictorVelarde commented
@Josmorsot. You should please take also this one, when you can

2022-01-21 08:44 UTC, Josmorsot commented on packages/react-ui/src/custom-components/InputFile.js
> +    for (let i = 0; i < items.length; i++) {
`items` is not an array, so instead using `forEach` I'm going to use a `for(item of items)`

2022-01-21 09:41 UTC, Josmorsot approved these changes

2022-01-21 09:55 UTC, merged