fix duplicated logic for category selection in HistogramWidgetUI
CartoDB/carto-react pull request #345
Opened 2022-02-18 15:59 UTC by juandjara

# Description

As with PR #332, this PR fixes the behaviour of HistogramWidgetUI `clickEvent`, removing duplicated logic that was re-appliying UI changes already applied in other `useEffect` calls. Before this changes, you couldn't recieve the `onSelectedBarsChange` event without affecting the UI of the chart. This change makes it so you can better control if the component is controlled or uncontrolled. 

## Type of change
- Fix

# Acceptance
Acceptance is described here in terms of the component API

1. create a constant array with `const categories = useRef([])`
2. Render a `<HistogramWidgetUI />`
3. Pass as props `selectedBars={categories.current}` and `onSelectedBarsChange={(value) => console.log(value)}`
4. When clicked, the UI of the chart should not be modified (the clicked part should not be highlighted)

# Basic checklist

- Good PR name
- Shortcut link
- Changelog entry
- Just one issue per PR
- GitHub labels
- Proper status & reviewers
- Tests
- Documentation

2022-02-21 07:49 UTC, Clebal requested changes
https://user-images.githubusercontent.com/9151432/154910948-eefbb546-aab4-44bd-a8f1-f1b54174a6ce.mov

I tested this PR using the template-sample-app-2 and it isn't working. Please, take a look.

2022-02-22 10:27 UTC, juandjara commented
Okay, finally I managed to get some time today to look at this. The thing was the `.filter` operation before the `.map` operation was changing the indexes to a weird something. Switching `map((d, i) => i)` with `map((d) => serie.data.indexOf(d))` fixes this.

2022-02-22 12:12 UTC, Clebal commented
https://user-images.githubusercontent.com/9151432/155129835-aec2a223-9a30-42e9-9985-dddf86340cf7.mov

It's working for every column except the last one. Can you take a look please?

2022-02-22 15:13 UTC, Clebal approved these changes

2022-02-22 15:18 UTC, merged