Update issue templates
CartoDB/carto-react pull request #484
Opened 2022-10-06 10:29 UTC by aaranadev

2022-10-06 18:33 UTC, alasarr commented on .github/ISSUE_TEMPLATE/bug_report.md
> +---
I miss here the environment and logs.

2022-10-06 18:33 UTC, alasarr commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
Just description

2022-10-06 18:41 UTC, alasarr requested changes
I feel issue forms would fit better

2022-10-07 06:51 UTC, aaranadev commented on .github/ISSUE_TEMPLATE/bug_report.md
> +---
Ok, no problem. The .md format is defined by the templates edit form of GitHub

<img width="1648" alt="Screenshot 2022-10-07 at 8 49 47 AM" src="https://user-images.githubusercontent.com/11427698/194485422-51885585-f2a5-4b30-9baf-ea6801a3dc56.png">

I'll change it to `yml`

2024-09-25 14:22 UTC, closed without merging